### PR TITLE
more of the staged records tagged

### PR DESCRIPTION
**Pull request by IzzySoft**
Hiho,

after a quite lengthy session, I've now tagged most of the *Bouncy Castle* record (those were quite a few!) A few I've left untagged as I couldn't identify them based on the recent version – so I'm not sure if they match that library. One additional entry staged and tagged (found in one of the `.apk` files I scanned). Hope everything fits again.

Btw: I had to throw away another planned PR as you did the same 3 lines in `detect.py` in parallel *LOL* Luckily I've noticed before commiting and pushing :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by IzzySoft** [comment]
Guess I'm putting in the breaks now again, before this batch gets to large. Once merged, I can create a new one. Still more than 20 libs in queue here :)

**Comment by pkumza** [comment]
👍  Thanks a lot for your efforts.

**Comment by IzzySoft** [comment]
You're welcome! Glad if I can "give something back" for what I "take" :)

**Comment by IzzySoft** [comment]
OK, no idea what GH did here, but the pulled-and-merged version of my repo is identical to yours. So as I wrote: please ignore the trouble, I'll just drop my fork and create a new, clean one to continue :)

**Pull request merged**
