### PR TITLE
fixed wrong definitions and added some new

### PR DESCRIPTION
**Pull request by IzzySoft**
* Glide (com/bumptech/glide) was erraneously assigned to Bump Pay
(com/bump)
* ftp4j lacked "lib" attribute

### CODE REVIEW

**Comment by pkumza** [comment]
I am trying to update V2's rules with V1.
like [`c5cd43e`](https://github.com/pkumza/LibRadar/commit/c5cd43eacbaf9f5721fe0af291861b31887ba46a)

**Comment by IzzySoft** [comment]
So I better keep creating those text files (see #30) for that, also with the next steps (`df`) for this, makes that job easier.

**Comment by pkumza** [comment]
> So I better keep creating those text files (see #30) for that
Oh yes. And it will be better when you keep `package name` with the rules.

**Comment by IzzySoft** [comment]
> And it will be better when you keep `package name` with the rules.

Uh? You mean in those text files? OK, can do that. As I've to process all those entries again anyway, I suggest to update those files along that and then make them available to you again:

* instead of the original mapping (`da` in almost all of the cases) I'd place the final "target mapping" (i.e. `ut`/`ui`/`df`) – or shall I rather keep the "original mapping" to make clear were it came from? The target becomes clear anyway, because …
* as before, I'd keep each "target group" in its own file for easier (sequential) handling
* after a separator of your choice (easiest would be space-hash-space, i.e. ` # `) I'd add the "pn", so it looks e.g. `ut;Foo Bar Example;http://example.com/ # com/foobar`

Does that match what you were pointing at? No big deal then – your wish shall be my command 😸

**Comment by pkumza** [comment]
>instead of the original mapping (da in almost all of the cases) I'd place the final "target mapping" (i.e. ut/ui/df) – or shall I rather keep the "original mapping" to make clear were it came from? The target becomes clear anyway, because …

In my opinion, original mapping is not important. So I suggest place the final "target mapping". What do you think?

>after a separator of your choice (easiest would be space-hash-space, i.e. #) I'd add the "pn", so it looks e.g. ut;Foo Bar Example;http://example.com/ # com/foobar

Yes. Keep `com/foo/bar` with the rules. It would be useful.

**Comment by IzzySoft** [comment]
> In my opinion, original mapping is not important. So I suggest place the final "target mapping". What do you think?

Too late, I think – I finished that job yesterday :flushed:

> Yes. Keep `com/foo/bar` with the rules. It would be useful.

That was done. I've also created a separate issue to collect the open tasks from this round of PRs, so we don't miss one of them. Just waiting for your "go" for them, and then will finish that ASAP.

**Comment by pkumza** [comment]
>Too late, I think – I finished that job yesterday 😳

Never mind, it's ok.

**Pull request merged**
